#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    May 23, 2022 11:17:38 AM CEST  platform: Windows NT

from tkinter import messagebox
import tkinter as tk
from tkinter import *
import os
import hashlib
import getpass

import antivirus_support

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'

        top.geometry("820x492")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(0,  0)
        top.title("oxa-antivirus")
        top.configure(background="#1F2732")
        top.iconbitmap('image/logo.ico')

        self.top = top
        username = (getpass.getuser())
        Donne1 = ('./base de donné/donné1.txt')
        locale = os.getenv('LOCALAPPDATA')
        desktop = "C:\\users\\" + username +"\\desktop"

        def scancomplet():
                try:
                    virus_found = False
                    print("analyse en cours")
                    dir_list = list()
                    for (dirpath, dirnames, filename) in os.walk(desktop):
                        dir_list += [os.path.join(dirpath, file) for file in filename]
                    for i in dir_list:
                        print(i)
                        with open(i, "rb") as f:
                            bytes = f.read()
                            readable_hash = hashlib.sha256(bytes).hexdigest();

                        with open(Donne1, 'r') as f:
                            lines = [line.rstrip() for line in f]
                            top.update()
                            self.Listboxscanning.delete(0, END)
                            self.Listboxscanning.insert(0, i)
                            for line in lines:
                                if str(readable_hash) == str(line.split(";")[0]):
                                    chemin = (i)
                                    print("liste des virus " + chemin)
                                    self.Listboxvirusfound.delete(0, END)
                                    self.Listboxvirusfound.insert(0, chemin)
                                    if messagebox.askyesno("Virus Trouvé", "virus trouvé voulez vous le supprimer ?") == True:
                                        os.remove(i)
                                    else:
                                        pass
                                    virus_found = True
                                    f.close()
                    print("analyse terminé")
                    if virus_found == False:
                        messagebox.showinfo("analyse", "aucun virus trouvé")
        # if virus_found == True:
        # messagebox.showwarning("virus trouvé", "virus trouvé ")
                except PermissionError:
                    pass




        self.menubar = tk.Menu(top,font="TkMenuFont",bg='#800080',fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.0, rely=0.085, relheight=0.929, relwidth=0.093)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="1")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#1F2732")
        self.Frame1.configure(highlightbackground="#000000")
        self.Frame1.configure(highlightcolor="#000040")

        self.Frame2 = tk.Frame(self.top)
        self.Frame2.place(relx=0.0, rely=-0.02, relheight=0.116, relwidth=1.005)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="1")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#1F2732")

        self.Label1 = tk.Label(self.Frame2)
        self.Label1.place(relx=0.0, rely=0.175, height=43, width=223)
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#1F2732")
        self.Label1.configure(borderwidth="0")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI Variable Text} -size 19 -weight bold")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(text='''OXA-ANTIVIRUS''')

        self.Buttonquitter = tk.Button(self.Frame2)
        self.Buttonquitter.place(relx=0.934, rely=0.175, height=44, width=57)
        self.Buttonquitter.configure(activebackground="#ececec")
        self.Buttonquitter.configure(activeforeground="#000000")
        self.Buttonquitter.configure(background="#d9d9d9")
        self.Buttonquitter.configure(compound='left')
        self.Buttonquitter.configure(cursor="fleur")
        self.Buttonquitter.configure(disabledforeground="#a3a3a3")
        self.Buttonquitter.configure(foreground="#000000")
        self.Buttonquitter.configure(highlightbackground="#d9d9d9")
        self.Buttonquitter.configure(highlightcolor="black")
        self.Buttonquitter.configure(pady="0")
        self.Buttonquitter.configure(text='''quitter''')

        self.Buttonreduire = tk.Button(self.Frame2)
        self.Buttonreduire.place(relx=0.874, rely=0.175, height=44, width=47)
        self.Buttonreduire.configure(activebackground="#ececec")
        self.Buttonreduire.configure(activeforeground="#000000")
        self.Buttonreduire.configure(background="#d9d9d9")
        self.Buttonreduire.configure(compound='left')
        self.Buttonreduire.configure(disabledforeground="#a3a3a3")
        self.Buttonreduire.configure(foreground="#000000")
        self.Buttonreduire.configure(highlightbackground="#d9d9d9")
        self.Buttonreduire.configure(highlightcolor="black")
        self.Buttonreduire.configure(pady="0")
        self.Buttonreduire.configure(text='''réduire''')

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.171, rely=0.732, height=54, width=227)
        self.Button1.configure(activebackground="#1F2732")
        self.Button1.configure(activeforeground="#ffffff")
        self.Button1.configure(background="#06A64A")
        self.Button1.configure(borderwidth="0")
        self.Button1.configure(compound='center')
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 14 -weight bold")
        self.Button1.configure(foreground="#ffffff")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(overrelief="solid")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Smart scan''',command=scancomplet)

        self.Button2 = tk.Button(self.top)
        self.Button2.place(relx=0.549, rely=0.732, height=54, width=227)
        self.Button2.configure(activebackground="#1F2732")
        self.Button2.configure(activeforeground="#ffffff")
        self.Button2.configure(background="#06A64A")
        self.Button2.configure(borderwidth="0")
        self.Button2.configure(compound='center')
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font="-family {Segoe UI} -size 14 -weight bold")
        self.Button2.configure(foreground="#ffffff")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''System Scan''')

        self.Frame3 = tk.Frame(self.top)
        self.Frame3.place(relx=0.293, rely=0.508, relheight=0.193
                , relwidth=0.417)
        self.Frame3.configure(relief="groove")
        self.Frame3.configure(background="#1F2732")
        self.Frame3.configure(cursor="fleur")

        self.Label2 = tk.Label(self.Frame3)
        self.Label2.place(relx=0.292, rely=0.095, height=24, width=154)
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#1F2732")
        self.Label2.configure(compound='center')
        self.Label2.configure(cursor="fleur")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI} -size 17")
        self.Label2.configure(foreground="#16b41e")
        self.Label2.configure(text='''Malware Scan''')

        self.Label3 = tk.Label(self.Frame3)
        self.Label3.place(relx=0.029, rely=0.474, height=46, width=324)
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#1F2732")
        self.Label3.configure(compound='left')
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font="-family {Segoe UI} -size 12")
        self.Label3.configure(foreground="#ffffff")
        self.Label3.configure(justify='left')
        self.Label3.configure(text='''Scan to ordinateur pour trouver malware
ransomware , ect...''')

        self.Label4 = tk.Label(self.top)
        self.Label4.place(relx=0.122, rely=0.122, height=41, width=124)
        self.Label4.configure(anchor='w')
        self.Label4.configure(background="#1F2732")
        self.Label4.configure(compound='left')
        self.Label4.configure(cursor="fleur")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font="-family {Segoe UI} -size 13 -weight bold")
        self.Label4.configure(foreground="#ffffff")
        self.Label4.configure(text='''Scanning file :''')

        self.Label5 = tk.Label(self.top)
        self.Label5.place(relx=0.122, rely=0.203, height=41, width=123)
        self.Label5.configure(anchor='w')
        self.Label5.configure(background="#1F2732")
        self.Label5.configure(compound='left')
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font="-family {Segoe UI} -size 13 -weight bold")
        self.Label5.configure(foreground="#ffffff")
        self.Label5.configure(text='''virus found :''')

        self.Listboxscanning = tk.Listbox(self.top)
        self.Listboxscanning.place(relx=0.28, rely=0.142, relheight=0.045
                , relwidth=0.684)
        self.Listboxscanning.configure(background="#1F2732")
        self.Listboxscanning.configure(borderwidth="0")
        self.Listboxscanning.configure(disabledforeground="#a3a3a3")
        self.Listboxscanning.configure(font="-family {Courier New} -size 10 -weight bold")
        self.Listboxscanning.configure(foreground="#ffffff")
        self.Listboxscanning.configure(highlightbackground="#1F2732")

        self.Listboxvirusfound = tk.Listbox(self.top)
        self.Listboxvirusfound.place(relx=0.28, rely=0.224, relheight=0.045
                , relwidth=0.683)
        self.Listboxvirusfound.configure(background="#1F2732")
        self.Listboxvirusfound.configure(borderwidth="0")
        self.Listboxvirusfound.configure(cursor="fleur")
        self.Listboxvirusfound.configure(disabledforeground="#a3a3a3")
        self.Listboxvirusfound.configure(font="-family {Courier New} -size 10 -weight bold")
        self.Listboxvirusfound.configure(foreground="#ffffff")
        self.Listboxvirusfound.configure(highlightbackground="#1F2732")

        self.Label6 = tk.Label(self.top)
        self.Label6.place(relx=0.098, rely=0.955, height=21, width=95)
        self.Label6.configure(anchor='w')
        self.Label6.configure(background="#1F2732")
        self.Label6.configure(compound='left')
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#ffffff")
        self.Label6.configure(text='''Made by freefox''')

def start_up():
    antivirus_support.main()

if __name__ == '__main__':
    antivirus_support.main()
